---
title: "Rapport RT-qPCR"
author: "Jérémie SUDOL"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r Library, include=FALSE}
library(tidyr)
library(ggplot2)
library(dplyr)
library(readr)
```

```{r Open data, include=FALSE}

qpcr_data<-read.csv2("C:/Users/jsnei/Desktop/Test_rapport/Rapports_1/data/clean/qpcr_data.csv", header = TRUE, sep = ';', dec = ',', stringsAsFactors = TRUE)

primer_key <- data.frame(row = c("A", "B", "C", "D", "E", "F", "G", "H"),
                         primers = c(rep("HK", 4), rep("test", 4)))
tidy_data <- separate(qpcr_data, Well, into = c("row", "column"), 
                      sep = 1, convert = TRUE)
tidy_data <- left_join(tidy_data, primer_key, by = "row")
```

```{r, Ct calculation}
tidy_data <- filter(tidy_data, Sample.Name != "NTC", Sample.Name != "")
```

```{r, Ct dans tableaux, include=FALSE}
summarised_data <- tidy_data %>%
  mutate(Ct = as.numeric(Ct)) %>%
  group_by(Sample.Name, primers) %>%
  summarise(mean_Ct = mean(Ct))
```

# Tables

```{r Tableaux}
head(tidy_data)
head(qpcr_data)
head(summarised_data)
```

# Plots

```{r Tables pour tableaux, include=FALSE}
#Figure 2
summarised_data <- summarised_data %>%
  separate(Sample.Name,into = c("RNAi", "replicate"), sep = "-")
```

You can also embed plots, for example:

```{r pressure, echo=FALSE, fig.height=20, fig.width=20}
ggplot(tidy_data, aes(x = column, y = row, fill = primers, label = Sample.Name)) +
  geom_tile(colour = "black") +
  geom_text() +
  scale_y_discrete(limits =  c("H", "G", "F", "E", "D", "C", "B", "A")) +
  scale_x_continuous(breaks = 1:12)

ggplot(summarised_data, aes(x = RNAi, y = mean_Ct, colour = primers)) +
  geom_point()

```

```{r Delta Ct, include=FALSE}
test_data <- summarised_data %>%
  filter(primers == "test")

ref_data <- summarised_data %>%
  filter(primers == "HK") %>%
  rename("ref_Ct" = "mean_Ct")

new_data <- left_join(test_data, ref_data, by = c( "RNAi", "replicate"))

new_data <- mutate(new_data, delta_Ct = ref_Ct - mean_Ct)
```

Le Ct des RNAi 1 et 2 comparés au contrôle.

```{r Ggplot Ct}
ggplot(new_data, aes(x = RNAi, y = delta_Ct)) +
  geom_point()
```

```{r Mean delta Ct for each treatment, include=FALSE}

treatment_summary <- new_data %>%
  group_by(RNAi) %>%
  summarise(mean_delta_Ct = mean(delta_Ct))

mean_control <- filter(treatment_summary, RNAi == "Control") %>% pull(mean_delta_Ct)

# Delta delta Ct
combined_data <- new_data %>% 
  mutate(delta_delta_Ct = mean_control - delta_Ct)
```

```{r Ggplot dd Ct}
ggplot(combined_data, aes(x = RNAi, y = delta_delta_Ct)) +
  geom_point()
```

```{r Calculating relative DNA concentration, include=FALSE}
combined_data <- combined_data %>%
  mutate(rel_conc = 2^-delta_delta_Ct)
```

```{r Relative DNA concentration}
ggplot(combined_data, aes(x = RNAi, y = rel_conc)) +
  geom_point() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1.3))
```

```{r Barplot with relative concentration, include=FALSE}
combined_data <- combined_data %>%
  group_by(RNAi) %>%
  mutate(mean_rel_conc = mean(rel_conc))
```

```{r Ggplot relative concentration}
ggplot(combined_data, aes(x = primers.x, y = mean_rel_conc, fill = RNAi, group = RNAi)) +
  geom_col(position ="dodge") +
  geom_point(aes(y = rel_conc), position = position_dodge(width = 0.9)) +
  scale_y_continuous("Relative concentration", labels = scales::percent) +
  scale_fill_manual("", values = c("Control" = "grey", "RNAi1" = "lightblue", "RNAi2" = "steelblue4")) +
  scale_x_discrete("") +
  ggtitle("qPCR analysis of knockdown for Test") +
  theme_classic(base_size = 12)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
